### ISSUE TITLE
Investigate: Missing default configuration

### ISSUE THREAD

**Issue by janrudolph** [assistify/smarti#13]
In one case, a new smarti client was empty. Smarti had not copied the default configuration. The smarti client was created through the Rocket.Chat application and not by the Smarti web interface.

**Comment by janrudolph** [comment]
Same behavior with another client. Log from Rocket.Chat Server

```
[34mI20171005-11:27:35.979(2) Exception in setTimeout callback: TypeError: func is not a function   at [object Object]._.extend.withValue (packages/meteor.js:1126:17)   at packages/meteor.js:445:51   at runWithEnvironment (packages/meteor.js:1180:24)  
[34mI20171009-14:20:45.254(2) Exception from sub stream-notify-room id uWutij8ihiyrt5j4C/typing TypeError: Cannot read property 't' of undefined   at [object Object].<anonymous> (/opt/Rocket.Chat/programs/server/packages/rocketchat_lib.js:4137:12)   at Streamer.isReadAllowed (/opt/Rocket.Chat/programs/server/packages/rocketchat_streamer.js:342:38)   at [object Object].<anonymous> (/opt/Rocket.Chat/programs/server/packages/rocketchat_streamer.js:477:16)   at [object Object].<anonymous> (/opt/Rocket.Chat/programs/server/packages/rocketchat_lib.js:1129:15)   at packages/matb33_collection-hooks.js:307:21   at [object Object]._.extend.withValue (packages/meteor.js:1126:17)   at [object Object]._handler (packages/matb33_collection-hooks.js:306:28)   at maybeAuditArgumentChecks (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:1858:12)   at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:1181:16   at [object Object]._.extend.withValue (packages/meteor.js:1126:17)   at [object Object]._.extend._runHandler (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:1180:51)   at [object Object]._.extend._startSubscription (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:1028:9)   at [object Object]._.extend.protocol_handlers.sub (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:816:12)   at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:754:85  
[34mI20171017-22:12:34.914(2) Exception from sub stream-room-messages id 78b4fb27-71ca-4ae4-a981-facb7e0df544 Error: Match error: Expected string, got null   at exports.check (packages/check.js:56:15)   at [object Object].<anonymous> (/opt/Rocket.Chat/programs/server/packages/rocketchat_streamer.js:469:5)   at [object Object].<anonymous> (/opt/Rocket.Chat/programs/server/packages/rocketchat_lib.js:1129:15)   at packages/matb33_collection-hooks.js:307:21   at [object Object]._.extend.withValue (packages/meteor.js:1126:17)   at [object Object]._handler (packages/matb33_collection-hooks.js:306:28)   at maybeAuditArgumentChecks (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:1858:12)   at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:1181:16   at [object Object]._.extend.withValue (packages/meteor.js:1126:17)   at [object Object]._.extend._runHandler (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:1180:51)   at [object Object]._.extend._startSubscription (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:1028:9)   at [object Object]._.extend.protocol_handlers.sub (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:816:12)   at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:754:85  
[34mI20171017-22:12:34.916(2) Sanitized and reported to the client as: Match failed [400] 
[34mI20171017-22:12:34.918(2) undefined undefined 
```
